sudo: false
language: node_js
cache:
  yarn: true
install:
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --ignore-engines
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6'
  - '5'
  - '4'
after_success: npm run coverage
